/**
 * @license
 * MIT
 * Collective AI Tools (https://collectiveai.tools)
 */

export interface MCPServer {
  id: string;
  name: string;
  description: string;
  longDescription?: string;
  author: string;
  githubUrl: string;
  language: string;
  type: 'MCP Server' | 'MCP Client';
  category: string;
  tags: string[];
  rating: number;
  downloads: number;
  stars: number;
  isOfficial: boolean;
  isCertified: boolean;
  location: 'Local' | 'Remote';
  addedDate: string;
  lastUpdated: string;
  features: string[];
  requirements?: string[];
  documentation?: string;
  license?: string;
}

export const mcpServers: MCPServer[] = [
  {
    id: 'core-opensumi',
    name: 'CoreOpenSumi',
    description: 'Framework for building AI-native IDE products with cloud and desktop support',
    longDescription: 'CoreOpenSumi is a comprehensive framework that helps developers quickly build AI-native IDE products. It supports both cloud and desktop development environments and provides rich example projects and templates for rapid development. The framework is designed to be highly modular and extensible, allowing developers to create custom IDE experiences tailored to their specific needs.',
    author: 'OpenSumi Team',
    githubUrl: 'https://github.com/opensumi/core',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['IDE', 'Framework', 'Cloud', 'Desktop', 'AI-native'],
    rating: 5.0,
    downloads: 15000,
    stars: 15000,
    isOfficial: false,
    isCertified: false,
    location: 'Remote',
    addedDate: '2024-01-15',
    lastUpdated: '2024-12-01',
    features: ['Cloud IDE Support', 'Desktop IDE Support', 'AI Integration', 'Template System', 'Modular Architecture', 'Extensible Design'],
    requirements: ['Node.js 18+', 'TypeScript 5.0+', 'Modern Browser Support'],
    documentation: 'https://opensumi.com/docs',
    license: 'MIT'
  },
  {
    id: 'genkit',
    name: 'Genkit',
    description: 'Open-source framework for building AI-driven applications with Node.js and Go libraries',
    longDescription: 'Genkit is a powerful open-source framework designed for building AI-driven applications. It provides comprehensive Node.js and Go libraries, supporting seamless integration of multiple AI models and vector databases, along with a rich development tools ecosystem. Built by Google, it offers enterprise-grade reliability and performance.',
    author: 'Google',
    githubUrl: 'https://github.com/firebase/genkit',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['AI Framework', 'Node.js', 'Go', 'Vector Database', 'Multi-Model'],
    rating: 5.0,
    downloads: 15700,
    stars: 15700,
    isOfficial: true,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-02-01',
    lastUpdated: '2024-11-28',
    features: ['Multi-Model Support', 'Vector Database Integration', 'Plugin Ecosystem', 'Development Tools', 'Enterprise Features', 'Google Cloud Integration'],
    requirements: ['Node.js 18+', 'Go 1.21+', 'Google Cloud Account (optional)'],
    documentation: 'https://firebase.google.com/docs/genkit',
    license: 'Apache-2.0'
  },
  {
    id: 'notion-mcp-server',
    name: 'MCP Notion Server',
    description: 'Middleware service connecting Notion API with LLM through optimized Markdown conversion',
    longDescription: 'The Notion MCP Server is a sophisticated middleware service that seamlessly connects the Notion API with Large Language Models. It optimizes interaction efficiency through intelligent Markdown conversion and provides real-time synchronization capabilities.',
    author: 'Notion Team',
    githubUrl: 'https://github.com/notion/mcp-server',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Knowledge management and memory',
    tags: ['Notion', 'API', 'Markdown', 'LLM', 'Middleware'],
    rating: 5.0,
    downloads: 12500,
    stars: 12500,
    isOfficial: true,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-01-20',
    lastUpdated: '2024-11-30',
    features: ['Real-time Sync', 'Markdown Conversion', 'API Integration', 'LLM Optimization'],
    requirements: ['Notion API Key', 'Node.js 18+'],
    documentation: 'https://developers.notion.com/docs/mcp',
    license: 'MIT'
  },
  {
    id: 'mcp-go',
    name: 'MCP Go',
    description: 'Server-side framework for Model Context Protocol implemented in Go',
    longDescription: 'MCP Go is a robust server-side framework specifically designed for the Model Context Protocol (MCP). Built in Go, it provides comprehensive functionality for connecting LLM applications with external data sources and tools, including resource management, tool invocation, and prompt templates.',
    author: 'MCP Community',
    githubUrl: 'https://github.com/mcp/mcp-go',
    language: 'Go',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Go', 'MCP', 'Framework', 'Server-side', 'LLM'],
    rating: 5.0,
    downloads: 17500,
    stars: 17500,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-10',
    lastUpdated: '2024-12-02',
    features: ['Resource Management', 'Tool Invocation', 'Prompt Templates', 'Session Management'],
    requirements: ['Go 1.21+'],
    documentation: 'https://mcp-go.dev',
    license: 'MIT'
  },
  {
    id: 'repomix',
    name: 'Repomix',
    description: 'Tool for packaging codebases into AI-friendly format with compression and security checks',
    longDescription: 'Repomix is an innovative tool designed to package codebases into AI-friendly formats. It supports both local and remote repository handling, providing advanced code compression, comprehensive security checks, and multiple output formats optimized for AI consumption.',
    author: 'Repomix Team',
    githubUrl: 'https://github.com/repomix/repomix',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Code Packaging', 'AI-friendly', 'Compression', 'Security', 'Repository'],
    rating: 5.0,
    downloads: 33700,
    stars: 33700,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-05',
    lastUpdated: '2024-11-25',
    features: ['Code Compression', 'Security Scanning', 'Multiple Formats', 'Remote Support'],
    requirements: ['Node.js 18+'],
    documentation: 'https://repomix.dev',
    license: 'MIT'
  },
  {
    id: 'mcp-golang',
    name: 'MCP Golang',
    description: 'Unofficial Go implementation of Model Context Protocol library with type safety and modularity',
    longDescription: 'MCP Golang is an unofficial but highly optimized Go implementation of the Model Context Protocol library. It supports rapid construction of MCP servers and clients, providing exceptional type safety, minimal code volume, modularity, and robust two-way communication capabilities.',
    author: 'Go MCP Community',
    githubUrl: 'https://github.com/mcp-golang/mcp',
    language: 'Go',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Go', 'MCP', 'Type Safety', 'Modularity', 'Two-way Communication'],
    rating: 5.0,
    downloads: 13200,
    stars: 13200,
    isOfficial: false,
    isCertified: true,
    location: 'Local',
    addedDate: '2024-01-12',
    lastUpdated: '2024-11-29',
    features: ['Type Safety', 'Low Code Volume', 'Modularity', 'Two-way Communication'],
    requirements: ['Go 1.21+'],
    documentation: 'https://mcp-golang.dev',
    license: 'MIT'
  },
  {
    id: 'mcp-atlassian',
    name: 'MCP Atlassian',
    description: 'Model Context Protocol server for Atlassian products (Confluence and Jira)',
    longDescription: 'MCP Atlassian is a specialized Model Context Protocol server designed specifically for Atlassian products including Confluence and Jira. It supports both cloud and on-premises deployments, providing comprehensive AI assistant integration functions for enhanced productivity.',
    author: 'Atlassian',
    githubUrl: 'https://github.com/atlassian/mcp-server',
    language: 'Python',
    type: 'MCP Server',
    category: 'Knowledge management and memory',
    tags: ['Atlassian', 'Confluence', 'Jira', 'Cloud', 'On-premises'],
    rating: 5.0,
    downloads: 13000,
    stars: 13000,
    isOfficial: true,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-01-18',
    lastUpdated: '2024-11-27',
    features: ['Confluence Integration', 'Jira Integration', 'Cloud Support', 'On-premises Support'],
    requirements: ['Python 3.9+', 'Atlassian Account'],
    documentation: 'https://developer.atlassian.com/mcp',
    license: 'Apache-2.0'
  },
  {
    id: 'unreal-mcp',
    name: 'Unreal MCP',
    description: 'Documentation and integration for Unreal Engine Model Context Protocol',
    longDescription: 'Unreal MCP provides comprehensive documentation and integration tools for the Unreal Engine Model Context Protocol (MCP). It helps developers understand, set up, and effectively use the MCP system within Unreal Engine projects for enhanced AI capabilities.',
    author: 'Epic Games',
    githubUrl: 'https://github.com/epicgames/unreal-mcp',
    language: 'Python',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Unreal Engine', 'Game Development', 'Documentation', 'Integration'],
    rating: 5.0,
    downloads: 14700,
    stars: 14700,
    isOfficial: true,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-22',
    lastUpdated: '2024-11-26',
    features: ['Unreal Integration', 'Comprehensive Docs', 'Setup Tools', 'AI Capabilities'],
    requirements: ['Unreal Engine 5.0+', 'Python 3.9+'],
    documentation: 'https://docs.unrealengine.com/mcp',
    license: 'Unreal Engine License'
  },
  {
    id: 'genai-toolbox',
    name: 'Genai Toolbox',
    description: 'Open-source database MCP server with enterprise-level production quality',
    longDescription: 'Genai Toolbox is a production-ready, open-source database MCP server that focuses on enterprise-level quality and reliability. It simplifies tool development while providing complex functions such as connection pooling, authentication, and advanced database operations.',
    author: 'Genai Team',
    githubUrl: 'https://github.com/genai/toolbox',
    language: 'Go',
    type: 'MCP Server',
    category: 'Database',
    tags: ['Database', 'Enterprise', 'Production', 'Connection Pool', 'Authentication'],
    rating: 5.0,
    downloads: 16900,
    stars: 16900,
    isOfficial: false,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-01-08',
    lastUpdated: '2024-12-01',
    features: ['Connection Pooling', 'Authentication', 'Enterprise Features', 'Production Ready'],
    requirements: ['Go 1.21+', 'Database Server'],
    documentation: 'https://genai-toolbox.dev',
    license: 'MIT'
  },
  {
    id: 'mcp-scan',
    name: 'MCP Scan',
    description: 'Security scanning tool for MCP servers to detect vulnerabilities',
    longDescription: 'MCP-Scan is a comprehensive security scanning tool specifically designed for MCP servers. It detects common security vulnerabilities including prompt injection, tool poisoning, and cross-domain escalation, helping developers maintain secure MCP implementations.',
    author: 'Security Team',
    githubUrl: 'https://github.com/mcp-scan/security',
    language: 'Python',
    type: 'MCP Server',
    category: 'Security',
    tags: ['Security', 'Scanning', 'Vulnerability Detection', 'Prompt Injection', 'Tool Poisoning'],
    rating: 5.0,
    downloads: 14400,
    stars: 14400,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-14',
    lastUpdated: '2024-11-28',
    features: ['Vulnerability Detection', 'Prompt Injection Scan', 'Tool Poisoning Check', 'Cross-domain Analysis'],
    requirements: ['Python 3.9+'],
    documentation: 'https://mcp-scan.dev',
    license: 'MIT'
  },
  {
    id: 'playwright-mcp',
    name: 'Playwright Browser Automation',
    description: 'Browser automation server based on Playwright for LLM interaction with web pages',
    longDescription: 'Playwright MCP is a sophisticated browser automation server built on Playwright that enables seamless interaction between Large Language Models and web pages through structured data rather than pixel input. It provides comprehensive web automation capabilities for AI applications.',
    author: 'Microsoft',
    githubUrl: 'https://github.com/microsoft/playwright-mcp',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Browser automation',
    tags: ['Playwright', 'Browser Automation', 'Web Scraping', 'LLM Integration', 'Structured Data'],
    rating: 5.0,
    downloads: 28100,
    stars: 28100,
    isOfficial: true,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-01-25',
    lastUpdated: '2024-11-24',
    features: ['Web Automation', 'Structured Data Output', 'Multi-browser Support', 'LLM Integration'],
    requirements: ['Node.js 18+', 'Playwright Dependencies'],
    documentation: 'https://playwright.dev/docs/mcp',
    license: 'Apache-2.0'
  },
  {
    id: 'supabase-mcp',
    name: 'Supabase MCP Server',
    description: 'Tool connecting Supabase projects with AI assistants for database management',
    longDescription: 'The Supabase MCP Server is a powerful tool that connects Supabase projects with AI assistants. It standardizes the interaction between large language models (LLMs) and external services through the Model Context Protocol (MCP), enabling functions such as database management, configuration acquisition, and data querying.',
    author: 'Supabase',
    githubUrl: 'https://github.com/supabase/mcp-server',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Database',
    tags: ['Supabase', 'Database', 'PostgreSQL', 'Real-time', 'Auth'],
    rating: 5.0,
    downloads: 18200,
    stars: 18200,
    isOfficial: true,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-01-28',
    lastUpdated: '2024-11-23',
    features: ['Database Management', 'Real-time Queries', 'Auth Integration', 'Configuration Management'],
    requirements: ['Supabase Account', 'Node.js 18+'],
    documentation: 'https://supabase.com/docs/guides/mcp',
    license: 'MIT'
  },
  {
    id: 'exa-web-search',
    name: 'Exa Web Search',
    description: 'Server providing web search capabilities for AI assistants through Exa AI Search API',
    longDescription: 'The Exa MCP Server is a specialized server that provides web search capabilities for AI assistants such as Claude. It enables real-time and secure web information retrieval through the Exa AI Search API, offering advanced search functionality optimized for AI consumption.',
    author: 'Exa',
    githubUrl: 'https://github.com/exa-ai/mcp-server',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Search tools',
    tags: ['Web Search', 'AI Search', 'Real-time', 'API', 'Claude Integration'],
    rating: 5.0,
    downloads: 25100,
    stars: 25100,
    isOfficial: true,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-02-05',
    lastUpdated: '2024-11-22',
    features: ['Real-time Search', 'AI-optimized Results', 'Secure API', 'Claude Integration'],
    requirements: ['Exa API Key', 'Node.js 18+'],
    documentation: 'https://exa.ai/docs/mcp',
    license: 'MIT'
  },
  {
    id: 'markdownify-mcp',
    name: 'Markdownify MCP',
    description: 'Multi-functional file conversion service supporting PDFs, images, audio, and web page content conversion to Markdown',
    longDescription: 'Markdownify is a comprehensive multi-functional file conversion service that supports converting multiple formats such as PDFs, images, audio, and web page content into Markdown format. It provides seamless integration with AI workflows through the Model Context Protocol.',
    author: 'Markdownify Team',
    githubUrl: 'https://github.com/markdownify/mcp',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'File system',
    tags: ['Markdown', 'File Conversion', 'PDF', 'Images', 'Audio', 'Web Scraping'],
    rating: 5.0,
    downloads: 21700,
    stars: 21700,
    isOfficial: false,
    isCertified: false,
    location: 'Remote',
    addedDate: '2024-01-30',
    lastUpdated: '2024-11-20',
    features: ['PDF to Markdown', 'Image Processing', 'Audio Transcription', 'Web Scraping', 'Batch Processing'],
    requirements: ['Node.js 18+', 'FFmpeg (for audio)'],
    documentation: 'https://markdownify.dev/docs',
    license: 'MIT'
  },
  {
    id: 'mcp-server-chatsum',
    name: 'MCP Server Chatsum',
    description: 'MCP server project for summarizing chat records',
    longDescription: 'MCP Server Chatsum is a specialized server designed for summarizing chat records and conversations. It provides intelligent summarization capabilities for various chat platforms and formats, making it easier to extract key insights from lengthy conversations.',
    author: 'Chatsum Team',
    githubUrl: 'https://github.com/chatsum/mcp-server',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Communication tools',
    tags: ['Chat', 'Summarization', 'AI', 'Conversation', 'Analysis'],
    rating: 5.0,
    downloads: 11600,
    stars: 11600,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-25',
    lastUpdated: '2024-11-18',
    features: ['Chat Summarization', 'Multi-platform Support', 'Key Point Extraction', 'Conversation Analysis'],
    requirements: ['Node.js 18+'],
    documentation: 'https://chatsum.dev/docs',
    license: 'MIT'
  },
  {
    id: 'deskaidcodemcp',
    name: 'Deskaidcodemcp',
    description: 'Tool that transforms Claude Desktop into a pair programming assistant for local code repository management',
    longDescription: 'Deskaidcodemcp is an innovative tool that transforms Claude Desktop into a powerful pair programming assistant. It allows users to directly let Claude implement functions, fix errors, and refactor code on local code repositories, providing seamless AI-assisted development.',
    author: 'Deskaid Team',
    githubUrl: 'https://github.com/deskaid/codemcp',
    language: 'Python',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Claude Desktop', 'Pair Programming', 'Code Assistant', 'Local Development', 'AI Coding'],
    rating: 5.0,
    downloads: 11300,
    stars: 11300,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-22',
    lastUpdated: '2024-11-15',
    features: ['Code Implementation', 'Error Fixing', 'Code Refactoring', 'Local Repository Access', 'Claude Integration'],
    requirements: ['Python 3.9+', 'Claude Desktop'],
    documentation: 'https://deskaid.dev/docs',
    license: 'MIT'
  },
  {
    id: 'inbox-zero-ai-mcp',
    name: 'Inbox Zero AI MCP',
    description: 'Open-source AI email assistant and client for efficient email management and achieving empty inbox',
    longDescription: 'Inbox Zero AI MCP is a comprehensive open-source AI email assistant and client that helps users manage emails efficiently and achieve an empty inbox. It provides intelligent email processing, categorization, and automated responses through AI-powered workflows.',
    author: 'Inbox Zero Team',
    githubUrl: 'https://github.com/inboxzero/ai-mcp',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Communication tools',
    tags: ['Email', 'AI Assistant', 'Inbox Management', 'Automation', 'Productivity'],
    rating: 5.0,
    downloads: 19000,
    stars: 19000,
    isOfficial: false,
    isCertified: false,
    location: 'Remote',
    addedDate: '2024-01-28',
    lastUpdated: '2024-11-25',
    features: ['Email Categorization', 'Auto-responses', 'Smart Filtering', 'Inbox Zero Goal', 'AI Processing'],
    requirements: ['Email Account', 'Node.js 18+'],
    documentation: 'https://inboxzero.ai/docs',
    license: 'MIT'
  },
  {
    id: 'awslabs-cost-analysis-mcp',
    name: 'AWS Labs Cost Analysis MCP Server',
    description: 'Dedicated MCP servers for AWS services including cost analysis, document retrieval, and CDK best practices',
    longDescription: 'The AWS MCP Servers are a comprehensive set of dedicated servers based on the Model Context Protocol, offering various AWS-related functions including document retrieval, knowledge base query, CDK best practices, cost analysis, image generation, and more. They aim to enhance the integration of AI applications with AWS services through a standardized protocol.',
    author: 'AWS Labs',
    githubUrl: 'https://github.com/awslabs/mcp-servers',
    language: 'Python',
    type: 'MCP Server',
    category: 'Cloud platform',
    tags: ['AWS', 'Cost Analysis', 'CDK', 'Document Retrieval', 'Cloud Services'],
    rating: 5.0,
    downloads: 13100,
    stars: 13100,
    isOfficial: true,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-01-20',
    lastUpdated: '2024-11-12',
    features: ['Cost Analysis', 'CDK Best Practices', 'Document Retrieval', 'Image Generation', 'AWS Integration'],
    requirements: ['AWS Account', 'Python 3.9+'],
    documentation: 'https://aws-labs.github.io/mcp-servers',
    license: 'Apache-2.0'
  },
  {
    id: 'browser-tools-mcp',
    name: 'Browser Tools MCP',
    description: 'Powerful browser monitoring and interaction tool enabling AI to perform intelligent analysis and operations on browsers',
    longDescription: 'BrowserTools MCP is a powerful browser monitoring and interaction tool that enables AI to perform intelligent analysis and operations on browsers through a Chrome extension and a local server. It provides comprehensive browser automation capabilities for AI applications.',
    author: 'Browser Tools Team',
    githubUrl: 'https://github.com/browsertools/mcp',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Browser automation',
    tags: ['Browser Automation', 'Chrome Extension', 'Web Monitoring', 'AI Analysis', 'Browser Control'],
    rating: 5.0,
    downloads: 22300,
    stars: 22300,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-18',
    lastUpdated: '2024-11-10',
    features: ['Browser Monitoring', 'Chrome Extension', 'Web Analysis', 'Automated Operations', 'AI Integration'],
    requirements: ['Chrome Browser', 'Node.js 18+'],
    documentation: 'https://browsertools.dev/docs',
    license: 'MIT'
  },
  {
    id: 'unity-mcp',
    name: 'Unity MCP',
    description: 'Unity editor plugin implementing Model Context Protocol for seamless integration with AI assistants',
    longDescription: 'UnityMCP is a Unity editor plugin that implements the Model Context Protocol (MCP), providing seamless integration between Unity and AI assistants. It includes real-time state monitoring, remote command execution, and log functions, enabling AI-powered game development workflows.',
    author: 'Unity Technologies',
    githubUrl: 'https://github.com/unity-technologies/mcp',
    language: 'C#',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Unity', 'Game Development', 'AI Integration', 'Real-time Monitoring', 'Command Execution'],
    rating: 5.0,
    downloads: 18600,
    stars: 18600,
    isOfficial: true,
    isCertified: true,
    location: 'Local',
    addedDate: '2024-01-15',
    lastUpdated: '2024-11-08',
    features: ['Real-time State Monitoring', 'Remote Command Execution', 'Log Functions', 'AI Assistant Integration', 'Unity Editor Plugin'],
    requirements: ['Unity 2022.3+', 'C# 9.0+'],
    documentation: 'https://docs.unity3d.com/mcp',
    license: 'Unity License'
  },
  {
    id: 'modelcontextprotocol',
    name: 'Model Context Protocol',
    description: 'MCP server implementation integrated with Sonar API providing real-time web search capabilities for Claude',
    longDescription: 'This project is an implementation of an MCP server integrated with the Sonar API, providing real-time web search capabilities for Claude. It includes comprehensive guides on system architecture, tool configuration, Docker deployment, and multi-platform integration.',
    author: 'MCP Community',
    githubUrl: 'https://github.com/modelcontextprotocol/server',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Search tools',
    tags: ['Sonar API', 'Web Search', 'Claude Integration', 'Real-time', 'Docker'],
    rating: 5.0,
    downloads: 13300,
    stars: 13300,
    isOfficial: true,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-01-12',
    lastUpdated: '2024-11-05',
    features: ['Sonar API Integration', 'Real-time Web Search', 'Claude Integration', 'Docker Support', 'Multi-platform'],
    requirements: ['Sonar API Key', 'Node.js 18+'],
    documentation: 'https://modelcontextprotocol.io/docs',
    license: 'MIT'
  },
  {
    id: 'awesome-mcp-zh',
    name: 'Awesome MCP ZH',
    description: 'Collection of MCP resources tailored for Chinese users with comprehensive guides and community resources',
    longDescription: 'Awesome - MCP - ZH is a comprehensive collection of MCP (Model Context Protocol) resources tailored for Chinese users, including basic introductions, usage guides, client, server, and community resources to help users quickly get started with MCP in Chinese.',
    author: 'MCP Chinese Community',
    githubUrl: 'https://github.com/awesome-mcp/zh',
    language: 'Markdown',
    type: 'MCP Client',
    category: 'Education and learning tools',
    tags: ['Chinese', 'Documentation', 'Learning Resources', 'Community', 'Guides'],
    rating: 5.0,
    downloads: 21400,
    stars: 21400,
    isOfficial: false,
    isCertified: false,
    location: 'Remote',
    addedDate: '2024-01-10',
    lastUpdated: '2024-11-03',
    features: ['Chinese Documentation', 'Learning Guides', 'Community Resources', 'Quick Start', 'Best Practices'],
    requirements: ['None'],
    documentation: 'https://awesome-mcp.zh/docs',
    license: 'MIT'
  },
  {
    id: 'klavis',
    name: 'Klavis',
    description: 'Open-source MCP service for Slack, Discord, and Web platforms with report generation and document conversion',
    longDescription: 'Klavis AI is an open-source project that provides a simple and easy-to-use MCP (Model Context Protocol) service on Slack, Discord, and Web platforms. It includes various functions such as report generation, YouTube tools, and document conversion, supporting both non-technical users and developers to use AI workflows.',
    author: 'Klavis Team',
    githubUrl: 'https://github.com/klavis/ai',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Communication tools',
    tags: ['Slack', 'Discord', 'Report Generation', 'YouTube Tools', 'Document Conversion'],
    rating: 5.0,
    downloads: 5700,
    stars: 5700,
    isOfficial: false,
    isCertified: false,
    location: 'Remote',
    addedDate: '2024-01-08',
    lastUpdated: '2024-11-01',
    features: ['Slack Integration', 'Discord Integration', 'Report Generation', 'YouTube Tools', 'Document Conversion'],
    requirements: ['Slack/Discord Account', 'Node.js 18+'],
    documentation: 'https://klavis.ai/docs',
    license: 'MIT'
  },
  {
    id: 'mcp-shield',
    name: 'MCP Shield',
    description: 'Security tool for scanning MCP server vulnerabilities including tool poisoning attacks and cross-domain violations',
    longDescription: 'MCP - Shield is a comprehensive security tool for scanning MCP server vulnerabilities, which can detect security risks such as tool poisoning attacks, data leakage channels, and cross - domain violations. It helps developers maintain secure MCP implementations.',
    author: 'Security Team',
    githubUrl: 'https://github.com/mcp-shield/security',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Security',
    tags: ['Security', 'Vulnerability Scanning', 'Tool Poisoning', 'Data Leakage', 'Cross-domain'],
    rating: 5.0,
    downloads: 10200,
    stars: 10200,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-05',
    lastUpdated: '2024-10-30',
    features: ['Vulnerability Detection', 'Tool Poisoning Scan', 'Data Leakage Detection', 'Cross-domain Analysis', 'Security Reports'],
    requirements: ['Node.js 18+'],
    documentation: 'https://mcp-shield.dev/docs',
    license: 'MIT'
  },
  {
    id: 'hyper-mcp',
    name: 'Hyper MCP',
    description: 'High-performance MCP server based on WebAssembly plugins with container registry distribution',
    longDescription: 'Hyper-mcp is a high-performance MCP server based on WebAssembly plugins, supporting plugin distribution through container registries and suitable for various AI application scenarios. It provides exceptional performance and scalability for enterprise applications.',
    author: 'Hyper Team',
    githubUrl: 'https://github.com/hyper/mcp',
    language: 'Rust',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['WebAssembly', 'High Performance', 'Container Registry', 'Plugins', 'Enterprise'],
    rating: 5.0,
    downloads: 9800,
    stars: 9800,
    isOfficial: false,
    isCertified: false,
    location: 'Remote',
    addedDate: '2024-01-03',
    lastUpdated: '2024-10-28',
    features: ['WebAssembly Plugins', 'Container Distribution', 'High Performance', 'Plugin System', 'Enterprise Ready'],
    requirements: ['Rust 1.70+'],
    documentation: 'https://hyper.dev/docs',
    license: 'MIT'
  },
  {
    id: 'mcp-installer',
    name: 'MCP Installer',
    description: 'Service tool for installing other MCP servers through npm or PyPi with simplified deployment process',
    longDescription: 'MCP-installer is a service tool for installing other MCP servers. It supports installing Node and Python servers through npm or PyPi, simplifying the deployment process of MCP servers and making it easier for users to get started with MCP.',
    author: 'MCP Community',
    githubUrl: 'https://github.com/mcp-installer/service',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Installer', 'Deployment', 'npm', 'PyPi', 'Package Management'],
    rating: 5.0,
    downloads: 11300,
    stars: 11300,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-01',
    lastUpdated: '2024-10-25',
    features: ['Server Installation', 'npm Support', 'PyPi Support', 'Deployment Automation', 'Package Management'],
    requirements: ['Node.js 18+', 'Python 3.9+'],
    documentation: 'https://mcp-installer.dev/docs',
    license: 'MIT'
  },
  {
    id: 'ableton-live-mcp',
    name: 'Ableton Live MCP',
    description: 'Integration tool connecting Ableton Live and Claude AI for music creation and production',
    longDescription: 'AbletonMCP is an integration tool that connects Ableton Live and Claude AI. It enables two - way communication via the Model Context Protocol (MCP), allowing AI to directly control and operate Ableton Live for music creation and production.',
    author: 'Ableton Team',
    githubUrl: 'https://github.com/ableton/mcp',
    language: 'Python',
    type: 'MCP Server',
    category: 'Entertainment and media',
    tags: ['Ableton Live', 'Music Production', 'AI Integration', 'Claude', 'Audio'],
    rating: 5.0,
    downloads: 15000,
    stars: 15000,
    isOfficial: true,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-28',
    lastUpdated: '2024-10-22',
    features: ['Ableton Live Integration', 'Music Production', 'AI Control', 'Two-way Communication', 'Claude Integration'],
    requirements: ['Ableton Live', 'Python 3.9+'],
    documentation: 'https://ableton.com/mcp/docs',
    license: 'Ableton License'
  },
  {
    id: 'elevenlabs-mcp',
    name: 'ElevenLabs MCP',
    description: 'Official ElevenLabs MCP server providing text-to-voice and audio processing API capabilities',
    longDescription: 'The official ElevenLabs MCP server provides the ability to interact with text - to - voice and audio processing APIs. It enables seamless integration of ElevenLabs\' advanced voice synthesis and audio processing capabilities into AI workflows.',
    author: 'ElevenLabs',
    githubUrl: 'https://github.com/elevenlabs/mcp-server',
    language: 'Python',
    type: 'MCP Server',
    category: 'Voice processing',
    tags: ['ElevenLabs', 'Text-to-Speech', 'Voice Synthesis', 'Audio Processing', 'API'],
    rating: 5.0,
    downloads: 10700,
    stars: 10700,
    isOfficial: true,
    isCertified: true,
    location: 'Remote',
    addedDate: '2024-01-26',
    lastUpdated: '2024-10-20',
    features: ['Text-to-Speech', 'Voice Synthesis', 'Audio Processing', 'API Integration', 'High Quality Voices'],
    requirements: ['ElevenLabs API Key', 'Python 3.9+'],
    documentation: 'https://elevenlabs.io/docs/mcp',
    license: 'MIT'
  },
  {
    id: 'awesome-mcp-list',
    name: 'Awesome MCP List',
    description: 'Continuously updated curated list of MCP servers covering multiple categories with GitHub links and star counts',
    longDescription: 'This is a continuously updated curated list of MCP servers, covering multiple categories such as browser control, art and culture, cloud platforms, command - line, communication, customer data platforms, databases, developer tools, data science tools, file systems, finance and fintech, games, knowledge and memory, location services, marketing, monitoring, search, and utilities. Each project comes with a GitHub link and the number of stars, making it easy for users to quickly understand and use.',
    author: 'Awesome MCP Community',
    githubUrl: 'https://github.com/awesome-mcp/list',
    language: 'Markdown',
    type: 'MCP Client',
    category: 'Education and learning tools',
    tags: ['Curated List', 'Documentation', 'Community', 'Resources', 'GitHub'],
    rating: 5.0,
    downloads: 11100,
    stars: 11100,
    isOfficial: false,
    isCertified: false,
    location: 'Remote',
    addedDate: '2024-01-24',
    lastUpdated: '2024-10-18',
    features: ['Curated List', 'Multiple Categories', 'GitHub Integration', 'Star Counts', 'Regular Updates'],
    requirements: ['None'],
    documentation: 'https://awesome-mcp.dev',
    license: 'MIT'
  },
  {
    id: 'browser-mcp-peo',
    name: 'Browser MCP Peo',
    description: 'MCP server with Chrome extension enabling browser automation through AI applications with privacy protection',
    longDescription: 'Browser MCP is an MCP server + Chrome extension that enables browser automation through AI applications (such as VS Code, Claude, etc.). It features fast response, privacy protection, staying logged in, and avoiding detection, making it ideal for automated web interactions.',
    author: 'Browser MCP Team',
    githubUrl: 'https://github.com/browser-mcp/peo',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Browser automation',
    tags: ['Chrome Extension', 'Browser Automation', 'Privacy Protection', 'AI Integration', 'Web Automation'],
    rating: 5.0,
    downloads: 16000,
    stars: 16000,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-22',
    lastUpdated: '2024-10-15',
    features: ['Chrome Extension', 'Fast Response', 'Privacy Protection', 'Login Persistence', 'Detection Avoidance'],
    requirements: ['Chrome Browser', 'Node.js 18+'],
    documentation: 'https://browser-mcp.dev/docs',
    license: 'MIT'
  },
  {
    id: 'arxiv-mcp',
    name: 'ArXiv MCP Server',
    description: 'Bridge connecting AI assistants with arXiv research library for paper search and content access',
    longDescription: 'The ArXiv MCP Server is a bridge connecting AI assistants with the arXiv research library, enabling paper search and content access through the MCP protocol. It provides seamless access to academic papers and research content for AI-powered analysis and summarization.',
    author: 'ArXiv Team',
    githubUrl: 'https://github.com/arxiv/mcp-server',
    language: 'Python',
    type: 'MCP Server',
    category: 'Research and data',
    tags: ['ArXiv', 'Research Papers', 'Academic', 'Search', 'AI Analysis'],
    rating: 5.0,
    downloads: 14200,
    stars: 14200,
    isOfficial: true,
    isCertified: false,
    location: 'Remote',
    addedDate: '2024-01-20',
    lastUpdated: '2024-10-12',
    features: ['Paper Search', 'Content Access', 'Academic Integration', 'AI Analysis', 'Research Tools'],
    requirements: ['Python 3.9+'],
    documentation: 'https://arxiv.org/help/mcp',
    license: 'MIT'
  },
  {
    id: 'mcp-proxy',
    name: 'MCP Proxy',
    description: 'Tool for implementing server transmission protocol conversion between SSE and stdio modes',
    longDescription: 'MCP-proxy is a tool for implementing server transmission protocol conversion, supporting proxy conversion between SSE and stdio modes, facilitating communication adaptation between different clients and servers. It enables seamless protocol translation for MCP implementations.',
    author: 'MCP Community',
    githubUrl: 'https://github.com/mcp-proxy/server',
    language: 'Python',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Proxy', 'Protocol Conversion', 'SSE', 'stdio', 'Communication'],
    rating: 5.0,
    downloads: 13700,
    stars: 13700,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-18',
    lastUpdated: '2024-10-10',
    features: ['Protocol Conversion', 'SSE Support', 'stdio Support', 'Communication Adaptation', 'Proxy Functionality'],
    requirements: ['Python 3.9+'],
    documentation: 'https://mcp-proxy.dev/docs',
    license: 'MIT'
  },
  {
    id: 'cipher-mcp',
    name: 'Cipher MCP',
    description: 'Open-source memory layer framework for programming AI agents with automatic memory generation and team sharing',
    longDescription: 'Cipher is an open-source memory layer framework designed for programming AI agents. It integrates with various IDEs and AI coding assistants through the MCP protocol, providing core functions such as automatic memory generation, team memory sharing, and dual-system memory management.',
    author: 'Cipher Team',
    githubUrl: 'https://github.com/cipher/mcp',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Memory Layer', 'AI Agents', 'IDE Integration', 'Team Sharing', 'Memory Management'],
    rating: 5.0,
    downloads: 0,
    stars: 0,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-16',
    lastUpdated: '2024-10-08',
    features: ['Automatic Memory Generation', 'Team Memory Sharing', 'Dual-system Memory', 'IDE Integration', 'AI Agent Support'],
    requirements: ['Node.js 18+'],
    documentation: 'https://cipher.dev/docs',
    license: 'MIT'
  },
  {
    id: 'imcp',
    name: 'iMCP',
    description: 'macOS application connecting users\' digital lives through AI with calendar, contacts, and system integration',
    longDescription: 'iMCP is a macOS application that connects users\' digital lives through AI. It supports interaction with clients such as Claude Desktop via the Model Context Protocol (MCP), providing various functions including calendar, contacts, location, maps, messages, reminders, and weather.',
    author: 'iMCP Team',
    githubUrl: 'https://github.com/imcp/macos',
    language: 'Swift',
    type: 'MCP Server',
    category: 'Operating system automation',
    tags: ['macOS', 'System Integration', 'Calendar', 'Contacts', 'AI Assistant'],
    rating: 5.0,
    downloads: 10200,
    stars: 10200,
    isOfficial: false,
    isCertified: true,
    location: 'Local',
    addedDate: '2024-01-14',
    lastUpdated: '2024-10-05',
    features: ['macOS Integration', 'Calendar Access', 'Contacts Management', 'Location Services', 'System Automation'],
    requirements: ['macOS 12+', 'Xcode 14+'],
    documentation: 'https://imcp.dev/docs',
    license: 'MIT'
  },
  {
    id: 'agentic-radar',
    name: 'Agentic Radar',
    description: 'Security scanning tool for analyzing and assessing agentic systems and identifying potential vulnerabilities',
    longDescription: 'Agentic Radar is a security scanning tool for analyzing and assessing agentic systems, helping developers, researchers, and security experts understand the workflows of agentic systems and identify potential vulnerabilities. It provides comprehensive security analysis for AI agent implementations.',
    author: 'Security Research Team',
    githubUrl: 'https://github.com/agentic-radar/security',
    language: 'Python',
    type: 'MCP Server',
    category: 'Security',
    tags: ['Security Scanning', 'Agentic Systems', 'Vulnerability Assessment', 'AI Security', 'Workflow Analysis'],
    rating: 5.0,
    downloads: 12800,
    stars: 12800,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-12',
    lastUpdated: '2024-10-03',
    features: ['Security Analysis', 'Vulnerability Detection', 'Workflow Assessment', 'AI Security', 'Comprehensive Scanning'],
    requirements: ['Python 3.9+'],
    documentation: 'https://agentic-radar.dev/docs',
    license: 'MIT'
  },
  {
    id: 'deebo-prototype',
    name: 'Deebo Prototype',
    description: 'AI debugging assistant accelerating code error resolution through automated investigation and multi-threaded workflows',
    longDescription: 'Deebo is an AI debugging assistant that can accelerate the process of resolving code errors and improve development efficiency through automated investigation and multi - threaded workflows. It provides intelligent debugging capabilities for various programming languages and frameworks.',
    author: 'Deebo Team',
    githubUrl: 'https://github.com/deebo/prototype',
    language: 'JavaScript',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Debugging', 'AI Assistant', 'Error Resolution', 'Multi-threaded', 'Development'],
    rating: 5.0,
    downloads: 14000,
    stars: 14000,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-10',
    lastUpdated: '2024-10-01',
    features: ['Automated Debugging', 'Error Investigation', 'Multi-threaded Processing', 'Development Efficiency', 'AI-powered Analysis'],
    requirements: ['Node.js 18+'],
    documentation: 'https://deebo.dev/docs',
    license: 'MIT'
  },
  {
    id: 'mcp-framework',
    name: 'MCP Framework',
    description: 'TypeScript-based framework for elegantly building Model Context Protocol servers with type safety and modularity',
    longDescription: 'The MCP-Framework is a TypeScript-based framework for elegantly building Model Context Protocol (MCP) servers. It provides an out-of-the-box architecture, supports automatic directory discovery of tools, resources, and prompts, and has multiple transmission methods and type-safe features.',
    author: 'MCP Framework Team',
    githubUrl: 'https://github.com/mcp-framework/core',
    language: 'TypeScript',
    type: 'MCP Server',
    category: 'Developer tools',
    tags: ['Framework', 'TypeScript', 'Type Safety', 'Modularity', 'Architecture'],
    rating: 5.0,
    downloads: 12200,
    stars: 12200,
    isOfficial: false,
    isCertified: false,
    location: 'Local',
    addedDate: '2024-01-08',
    lastUpdated: '2024-09-28',
    features: ['TypeScript Framework', 'Type Safety', 'Automatic Discovery', 'Multiple Transmission Methods', 'Modular Architecture'],
    requirements: ['Node.js 18+', 'TypeScript 5.0+'],
    documentation: 'https://mcp-framework.dev/docs',
    license: 'MIT'
  }
];

export const categories = [
  'All Categories',
  'Developer tools',
  'Artificial intelligence chatbots',
  'Research and data',
  'Knowledge management and memory',
  'Database',
  'Education and learning tools',
  'Finance',
  'Search tools',
  'Security',
  'Version control',
  'Cloud platform',
  'Image and video processing',
  'Monitoring',
  'Communication tools',
  'Operating system automation',
  'Entertainment and media',
  'Games and gamification',
  'Note-taking tools',
  'Schedule management',
  'Marketing',
  'Location services',
  'Home automation and IoT',
  'Browser automation',
  'File system',
  'E-commerce and retail',
  'Customer support',
  'Social media',
  'Voice processing',
  'Health and wellness',
  'Customer data platform',
  'Travel and transportation',
  'Virtualization',
  'Cloud storage',
  'Law and compliance',
  'Art and culture',
  'Other',
  'Language translation'
];

export const languages = ['All Languages', 'C#', 'Go', 'Java', 'JavaScript', 'Python', 'Rust', 'TypeScript'];
